name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy with gh-pages
      run: |
        
        # Deploy the contents of the 'build' directory to GitHub Page
        git config --local user.email "Amrita.Saha@itcinfotech.com"

        git config --local user.name "Amrita0987"
        echo "Using Github Token: $GITHUB_TOKEN"
        git clone https://github.com/Amrita0987/github-actions-node.git
        git remote set-url origin "https://git:$GITHUB_TOKEN@github.com/Amrita0987/github-actions-node.git"
        npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
