name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy with gh-pages
      run: |
        
        # Deploy the contents of the 'build' directory to GitHub Page
        git config --local user.email "Amrita.Saha@itcinfotech.com"

        git config --local user.name "Amrita0987"

        git checkout --orphan gh-pages

        git rm -rf .

        mv build/* .

        git add .

        git commit -m "Deploy to GitHub Pages"

        git branch -M gh-pages

        git push -f origin gh-pages
